// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v7.36.2
// source: api/adapter/v1/adapter.proto

package adapterv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DescribeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DescribeRequest) Reset() {
	*x = DescribeRequest{}
	mi := &file_api_adapter_v1_adapter_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DescribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DescribeRequest) ProtoMessage() {}

func (x *DescribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_adapter_v1_adapter_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DescribeRequest.ProtoReflect.Descriptor instead.
func (*DescribeRequest) Descriptor() ([]byte, []int) {
	return file_api_adapter_v1_adapter_proto_rawDescGZIP(), []int{0}
}

type Provider struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Authentication string                 `protobuf:"bytes,2,opt,name=authentication,proto3" json:"authentication,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Provider) Reset() {
	*x = Provider{}
	mi := &file_api_adapter_v1_adapter_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Provider) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Provider) ProtoMessage() {}

func (x *Provider) ProtoReflect() protoreflect.Message {
	mi := &file_api_adapter_v1_adapter_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Provider.ProtoReflect.Descriptor instead.
func (*Provider) Descriptor() ([]byte, []int) {
	return file_api_adapter_v1_adapter_proto_rawDescGZIP(), []int{1}
}

func (x *Provider) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Provider) GetAuthentication() string {
	if x != nil {
		return x.Authentication
	}
	return ""
}

type DescribeResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ProtocolVersion string                 `protobuf:"bytes,1,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	AdapterId       string                 `protobuf:"bytes,2,opt,name=adapter_id,json=adapterId,proto3" json:"adapter_id,omitempty"`
	Version         string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	Hosts           []string               `protobuf:"bytes,4,rep,name=hosts,proto3" json:"hosts,omitempty"`
	Providers       []*Provider            `protobuf:"bytes,5,rep,name=providers,proto3" json:"providers,omitempty"`
	Capabilities    []string               `protobuf:"bytes,6,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *DescribeResponse) Reset() {
	*x = DescribeResponse{}
	mi := &file_api_adapter_v1_adapter_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DescribeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DescribeResponse) ProtoMessage() {}

func (x *DescribeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_adapter_v1_adapter_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DescribeResponse.ProtoReflect.Descriptor instead.
func (*DescribeResponse) Descriptor() ([]byte, []int) {
	return file_api_adapter_v1_adapter_proto_rawDescGZIP(), []int{2}
}

func (x *DescribeResponse) GetProtocolVersion() string {
	if x != nil {
		return x.ProtocolVersion
	}
	return ""
}

func (x *DescribeResponse) GetAdapterId() string {
	if x != nil {
		return x.AdapterId
	}
	return ""
}

func (x *DescribeResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *DescribeResponse) GetHosts() []string {
	if x != nil {
		return x.Hosts
	}
	return nil
}

func (x *DescribeResponse) GetProviders() []*Provider {
	if x != nil {
		return x.Providers
	}
	return nil
}

func (x *DescribeResponse) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

type FetchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	ExternalId    string                 `protobuf:"bytes,2,opt,name=external_id,json=externalId,proto3" json:"external_id,omitempty"`
	ProviderId    string                 `protobuf:"bytes,3,opt,name=provider_id,json=providerId,proto3" json:"provider_id,omitempty"`
	ConnectionId  string                 `protobuf:"bytes,4,opt,name=connection_id,json=connectionId,proto3" json:"connection_id,omitempty"`
	AccessScope   string                 `protobuf:"bytes,5,opt,name=access_scope,json=accessScope,proto3" json:"access_scope,omitempty"`
	RequestId     string                 `protobuf:"bytes,6,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchRequest) Reset() {
	*x = FetchRequest{}
	mi := &file_api_adapter_v1_adapter_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchRequest) ProtoMessage() {}

func (x *FetchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_adapter_v1_adapter_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchRequest.ProtoReflect.Descriptor instead.
func (*FetchRequest) Descriptor() ([]byte, []int) {
	return file_api_adapter_v1_adapter_proto_rawDescGZIP(), []int{3}
}

func (x *FetchRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *FetchRequest) GetExternalId() string {
	if x != nil {
		return x.ExternalId
	}
	return ""
}

func (x *FetchRequest) GetProviderId() string {
	if x != nil {
		return x.ProviderId
	}
	return ""
}

func (x *FetchRequest) GetConnectionId() string {
	if x != nil {
		return x.ConnectionId
	}
	return ""
}

func (x *FetchRequest) GetAccessScope() string {
	if x != nil {
		return x.AccessScope
	}
	return ""
}

func (x *FetchRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

type Resource struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Kind          string                 `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Resource) Reset() {
	*x = Resource{}
	mi := &file_api_adapter_v1_adapter_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Resource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Resource) ProtoMessage() {}

func (x *Resource) ProtoReflect() protoreflect.Message {
	mi := &file_api_adapter_v1_adapter_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Resource.ProtoReflect.Descriptor instead.
func (*Resource) Descriptor() ([]byte, []int) {
	return file_api_adapter_v1_adapter_proto_rawDescGZIP(), []int{4}
}

func (x *Resource) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *Resource) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

type FetchResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ExternalId     string                 `protobuf:"bytes,1,opt,name=external_id,json=externalId,proto3" json:"external_id,omitempty"`
	Text           string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	TextKind       string                 `protobuf:"bytes,3,opt,name=text_kind,json=textKind,proto3" json:"text_kind,omitempty"`
	Resources      []*Resource            `protobuf:"bytes,4,rep,name=resources,proto3" json:"resources,omitempty"`
	Warnings       []string               `protobuf:"bytes,5,rep,name=warnings,proto3" json:"warnings,omitempty"`
	ProviderId     string                 `protobuf:"bytes,6,opt,name=provider_id,json=providerId,proto3" json:"provider_id,omitempty"`
	AdapterVersion string                 `protobuf:"bytes,7,opt,name=adapter_version,json=adapterVersion,proto3" json:"adapter_version,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *FetchResponse) Reset() {
	*x = FetchResponse{}
	mi := &file_api_adapter_v1_adapter_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchResponse) ProtoMessage() {}

func (x *FetchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_adapter_v1_adapter_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchResponse.ProtoReflect.Descriptor instead.
func (*FetchResponse) Descriptor() ([]byte, []int) {
	return file_api_adapter_v1_adapter_proto_rawDescGZIP(), []int{5}
}

func (x *FetchResponse) GetExternalId() string {
	if x != nil {
		return x.ExternalId
	}
	return ""
}

func (x *FetchResponse) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *FetchResponse) GetTextKind() string {
	if x != nil {
		return x.TextKind
	}
	return ""
}

func (x *FetchResponse) GetResources() []*Resource {
	if x != nil {
		return x.Resources
	}
	return nil
}

func (x *FetchResponse) GetWarnings() []string {
	if x != nil {
		return x.Warnings
	}
	return nil
}

func (x *FetchResponse) GetProviderId() string {
	if x != nil {
		return x.ProviderId
	}
	return ""
}

func (x *FetchResponse) GetAdapterVersion() string {
	if x != nil {
		return x.AdapterVersion
	}
	return ""
}

var File_api_adapter_v1_adapter_proto protoreflect.FileDescriptor

const file_api_adapter_v1_adapter_proto_rawDesc = "" +
	"\n" +
	"\x1capi/adapter/v1/adapter.proto\x12\n" +
	"adapter.v1\"\x11\n" +
	"\x0fDescribeRequest\"B\n" +
	"\bProvider\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12&\n" +
	"\x0eauthentication\x18\x02 \x01(\tR\x0eauthentication\"\xe4\x01\n" +
	"\x10DescribeResponse\x12)\n" +
	"\x10protocol_version\x18\x01 \x01(\tR\x0fprotocolVersion\x12\x1d\n" +
	"\n" +
	"adapter_id\x18\x02 \x01(\tR\tadapterId\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x12\x14\n" +
	"\x05hosts\x18\x04 \x03(\tR\x05hosts\x122\n" +
	"\tproviders\x18\x05 \x03(\v2\x14.adapter.v1.ProviderR\tproviders\x12\"\n" +
	"\fcapabilities\x18\x06 \x03(\tR\fcapabilities\"\xc9\x01\n" +
	"\fFetchRequest\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12\x1f\n" +
	"\vexternal_id\x18\x02 \x01(\tR\n" +
	"externalId\x12\x1f\n" +
	"\vprovider_id\x18\x03 \x01(\tR\n" +
	"providerId\x12#\n" +
	"\rconnection_id\x18\x04 \x01(\tR\fconnectionId\x12!\n" +
	"\faccess_scope\x18\x05 \x01(\tR\vaccessScope\x12\x1d\n" +
	"\n" +
	"request_id\x18\x06 \x01(\tR\trequestId\"0\n" +
	"\bResource\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12\x12\n" +
	"\x04kind\x18\x02 \x01(\tR\x04kind\"\xfb\x01\n" +
	"\rFetchResponse\x12\x1f\n" +
	"\vexternal_id\x18\x01 \x01(\tR\n" +
	"externalId\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\x12\x1b\n" +
	"\ttext_kind\x18\x03 \x01(\tR\btextKind\x122\n" +
	"\tresources\x18\x04 \x03(\v2\x14.adapter.v1.ResourceR\tresources\x12\x1a\n" +
	"\bwarnings\x18\x05 \x03(\tR\bwarnings\x12\x1f\n" +
	"\vprovider_id\x18\x06 \x01(\tR\n" +
	"providerId\x12'\n" +
	"\x0fadapter_version\x18\a \x01(\tR\x0eadapterVersion2\x8e\x01\n" +
	"\aAdapter\x12E\n" +
	"\bDescribe\x12\x1b.adapter.v1.DescribeRequest\x1a\x1c.adapter.v1.DescribeResponse\x12<\n" +
	"\x05Fetch\x12\x18.adapter.v1.FetchRequest\x1a\x19.adapter.v1.FetchResponseB\"Z monitor/api/adapter/v1;adapterv1b\x06proto3"

var (
	file_api_adapter_v1_adapter_proto_rawDescOnce sync.Once
	file_api_adapter_v1_adapter_proto_rawDescData []byte
)

func file_api_adapter_v1_adapter_proto_rawDescGZIP() []byte {
	file_api_adapter_v1_adapter_proto_rawDescOnce.Do(func() {
		file_api_adapter_v1_adapter_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_adapter_v1_adapter_proto_rawDesc), len(file_api_adapter_v1_adapter_proto_rawDesc)))
	})
	return file_api_adapter_v1_adapter_proto_rawDescData
}

var file_api_adapter_v1_adapter_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_api_adapter_v1_adapter_proto_goTypes = []any{
	(*DescribeRequest)(nil),  // 0: adapter.v1.DescribeRequest
	(*Provider)(nil),         // 1: adapter.v1.Provider
	(*DescribeResponse)(nil), // 2: adapter.v1.DescribeResponse
	(*FetchRequest)(nil),     // 3: adapter.v1.FetchRequest
	(*Resource)(nil),         // 4: adapter.v1.Resource
	(*FetchResponse)(nil),    // 5: adapter.v1.FetchResponse
}
var file_api_adapter_v1_adapter_proto_depIdxs = []int32{
	1, // 0: adapter.v1.DescribeResponse.providers:type_name -> adapter.v1.Provider
	4, // 1: adapter.v1.FetchResponse.resources:type_name -> adapter.v1.Resource
	0, // 2: adapter.v1.Adapter.Describe:input_type -> adapter.v1.DescribeRequest
	3, // 3: adapter.v1.Adapter.Fetch:input_type -> adapter.v1.FetchRequest
	2, // 4: adapter.v1.Adapter.Describe:output_type -> adapter.v1.DescribeResponse
	5, // 5: adapter.v1.Adapter.Fetch:output_type -> adapter.v1.FetchResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_api_adapter_v1_adapter_proto_init() }
func file_api_adapter_v1_adapter_proto_init() {
	if File_api_adapter_v1_adapter_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_adapter_v1_adapter_proto_rawDesc), len(file_api_adapter_v1_adapter_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_adapter_v1_adapter_proto_goTypes,
		DependencyIndexes: file_api_adapter_v1_adapter_proto_depIdxs,
		MessageInfos:      file_api_adapter_v1_adapter_proto_msgTypes,
	}.Build()
	File_api_adapter_v1_adapter_proto = out.File
	file_api_adapter_v1_adapter_proto_goTypes = nil
	file_api_adapter_v1_adapter_proto_depIdxs = nil
}
