#!/usr/bin/env python3
"""Verify that pre-commit checks the index without disturbing partial staging."""

from pathlib import Path
import shutil
import subprocess
import sys
import tempfile
import unittest

ROOT = Path(__file__).resolve().parent.parent
FORMATTED = '{\n  "value": 1\n}\n'
UNFORMATTED = '{"value":1}'


class FormatHookTest(unittest.TestCase):
    def setUp(self):
        self.directory = tempfile.TemporaryDirectory()
        self.addCleanup(self.directory.cleanup)
        self.root = Path(self.directory.name)
        (self.root / "scripts").mkdir()
        (self.root / ".githooks").mkdir()
        shutil.copy2(ROOT / "scripts/format.py", self.root / "scripts/format.py")
        shutil.copy2(ROOT / ".githooks/pre-commit", self.root / ".githooks/pre-commit")
        (self.root / "node_modules").symlink_to(
            ROOT / "node_modules", target_is_directory=True
        )
        self.git("init", "--quiet")
        self.git("config", "core.hooksPath", ".githooks")
        self.git("config", "user.name", "Format Test")
        self.git("config", "user.email", "format-test@example.invalid")

    def git(self, *args, check=True):
        return subprocess.run(
            ["git", *args], cwd=self.root, capture_output=True, check=check
        )

    def stage(self, text):
        (self.root / "sample.json").write_text(text)
        self.git("add", "sample.json")

    def test_rejects_unformatted_index_even_if_worktree_is_formatted(self):
        self.stage(UNFORMATTED)
        (self.root / "sample.json").write_text(FORMATTED)
        index = self.git("ls-files", "--stage").stdout
        result = self.git("commit", "-m", "must reject", check=False)
        self.assertNotEqual(result.returncode, 0)
        self.assertIn(b"Needs formatting: sample.json", result.stdout + result.stderr)
        self.assertEqual(self.git("ls-files", "--stage").stdout, index)
        self.assertEqual((self.root / "sample.json").read_text(), FORMATTED)
        self.assertEqual(self.git("show", ":sample.json").stdout.decode(), UNFORMATTED)

    def test_go_formatting_converges_before_writing(self):
        if (ROOT / ".tools").exists():
            (self.root / ".tools").symlink_to(ROOT / ".tools", target_is_directory=True)
        path = self.root / "generated.go"
        path.write_text(
            "// Code generated by test. DO NOT EDIT.\n"
            "package sample\n\n"
            "var a = 1\nvar b = 2\nvar c = []int{\n1,\n}\n"
            "var d = []int{\n2,\n}\n"
        )
        command = [sys.executable, "scripts/format.py"]
        subprocess.run(
            [*command, "--write", "generated.go"],
            cwd=self.root,
            check=True,
            capture_output=True,
        )
        formatted = path.read_bytes()
        subprocess.run(
            [*command, "--check", "generated.go"],
            cwd=self.root,
            check=True,
            capture_output=True,
        )
        subprocess.run(
            [*command, "--write", "generated.go"],
            cwd=self.root,
            check=True,
            capture_output=True,
        )
        self.assertEqual(path.read_bytes(), formatted)
        self.git("add", "generated.go")
        self.git("commit", "-m", "formatted generated Go")

    def test_accepts_formatted_index_without_staging_worktree_changes(self):
        self.stage(FORMATTED)
        (self.root / "sample.json").write_text(UNFORMATTED)
        self.git("commit", "-m", "formatted index")
        self.assertEqual(
            self.git("show", "HEAD:sample.json").stdout.decode(), FORMATTED
        )
        self.assertEqual((self.root / "sample.json").read_text(), UNFORMATTED)
        self.assertEqual(self.git("diff", "--cached").stdout, b"")


if __name__ == "__main__":
    unittest.main()
